### ISSUE TITLE
bug(Purpur): NPE on updater#setChannel

### ISSUE THREAD

**Issue by voidpointer0x00** [lenis0012/LoginSecurity#311]
I guess there's no updater available for Purpur servers :)

https://github.com/lenis0012/LoginSecurity/blob/b003ca6ab632a7ddd30cf9bea3afb6deef401244/src/main/java/com/lenis0012/bukkit/loginsecurity/modules/general/GeneralModule.java#L66-L71

**Comment by lenis0012** [comment]
You need to pick one when compiling using `mvn package -Pspigot` or `mvn package -Pbukkit` (spigot should be used in most cases)

**Comment by lenis0012** [comment]
I am planning to add a no-op updater as fallback probably in v3.3
