### ISSUE TITLE
Is it up to date?

### ISSUE THREAD

**Issue by Shawal13** [lenis0012/LoginSecurity#322]
so whenever I try to start my server it says [07:44:48 ERROR]: Error occurred while enabling LoginSecurity v3.2.1 (Is it up to date?) and give a crash dump and just stop the Login security please tell if you know the solution!

**Comment by lenis0012** [comment]
Is it up to date is just a hint to server owners to check if they are using the latest version of a plugin before reporting any errors.

I can't help you without having the contents of the error message. There should be a bunch of additional content printed after the error message, this is called a "stack trace". It would be nice if you could post that in here so I can take a look at your issue.

**Comment by lenis0012** [comment]
going to close this issue due to getting no additional formation.
If you are still able and willing or provide this information (server / error logs) please feel free to open a new issue
